In [1]:
import torch
import torch.nn.functional as F
import numpy as np
import os
print("ok")

ok


In [ ]:
a = torch.Tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.Tensor([[2, 3, 4],
                  [1, 4, 5]])
l2规范化a, l2规范化b = F.normalize(a, dim=-1), F.normalize(b, dim=-1)
print("l2规范化a")
print(l2规范化a)
print("l2规范化b")
print(l2规范化b)
print('\n')
拼接 = torch.cat([l2规范化a, l2规范化b], dim=0)
# out.t().contiguous()矩阵转置后以行优先形式在内存中连续存储。
# 计算余弦相似性，对角线表示每个图像自己和自己的相似性，需要去掉
sim_matrix = torch.exp(torch.mm(拼接, 拼接.t().contiguous())) # 形状[2*batch_size, 2*batch_size]
print("内积矩阵")
print(sim_matrix)
print('\n')
# torch.ones_like()根据给定的张量生成全是1的张量，torch.eye()生成指定大小和类型的对角线全是1的2维张量。
# mask是对角线全False，其余全True的张量
mask = (torch.ones_like(sim_matrix) - torch.eye(2 * 2, device=sim_matrix.device)).bool()

# 根据给定的掩码张量的二元值，取出输入张量中对应位置的值，这里就是去掉对角线的值，返回一个行优先排列的一维张量。
# 然后改变形状，得到真正的余弦相似性矩阵，
sim_matrix = sim_matrix.masked_select(mask).view(2 * 2, -1)# 形状[2*batch_size, 2*batch_size-1]
print("相似矩阵")
print(sim_matrix)
print('\n')

print("相似矩阵行求和")
print(sim_matrix.sum(dim=-1))
print('\n')

print("规范化相乘再行求和")
pos_sim = torch.exp(torch.sum(l2规范化a * l2规范化b, dim=-1)) # 形状[1*batch_size]
print(pos_sim)
print('\n')

# [2*B]
pos_sim = torch.cat([pos_sim, pos_sim], dim=0)
print("拼接")
print(pos_sim)
print('\n')
结果 = (- torch.log(pos_sim / sim_matrix.sum(dim=-1))).mean()
print(结果)
print(- torch.log(pos_sim / sim_matrix.sum(dim=-1)))

In [3]:
a = torch.Tensor([1, 2, 3])
b = torch.Tensor([2, 4, 5])
print(torch.cat((a, b),dim=0))

tensor([1., 2., 3., 2., 4., 5.])


In [4]:
A=torch.ones(2,3)    #2x3的张量（矩阵）
print("A:\n",A,"\nA.shape:\n",A.shape,"\n")

B=2*torch.ones(4,3)  #4x3的张量（矩阵）
print("B:\n",B,"\nB.shape:\n",B.shape,"\n")

C=torch.cat((A,B),0)  #按维数0（行）拼接
print("C:\n",C,"\nC.shape:\n",C.shape,"\n")

A:
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
A.shape:
 torch.Size([2, 3]) 

B:
 tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]) 
B.shape:
 torch.Size([4, 3]) 

C:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]) 
C.shape:
 torch.Size([6, 3]) 



In [25]:
a = torch.Tensor([[1, 1, 3],
                  [2, 2, 4],
                  [3, 4, 9]])
掩码 = (torch.ones_like(a) - torch.eye(3)).bool()
# print(掩码)
print(torch.masked_select(a, 掩码))
# print(掩码)
print(a.sum(dim=-1))
print(torch.sum(a, dim=-1))
print(torch.sum(a, dim=1))

tensor([1., 3., 2., 4., 3., 4.])
tensor([ 5.,  8., 16.])
tensor([ 5.,  8., 16.])
tensor([ 5.,  8., 16.])


In [39]:
a = torch.Tensor([1 ,2 ,3])
print(torch.log(a))
b = (torch.log(a)).mean()
print(b)
c = torch.Tensor([0.3356])
print(-torch.log(c))

tensor([0.0000, 0.6931, 1.0986])
tensor(0.5973)
tensor([1.0918])


In [8]:
a = np.array([[[1, 2, 3, 4, 5],
               [2 ,3 ,4 ,5 ,6],
               [3, 4, 5, 6, 7]],

              [[2, 3, 4, 5, 6],
               [3, 4, 5, 6, 7],
               [4, 5, 6, 7, 8]],

              [[0, 1, 2, 3, 4],
               [1, 2, 3, 4, 5],
               [2, 2, 2, 2, 2]]])
# b = a[-1, :, :]
for i in a[-1, :, :]:
    print("?")
    print(i)

?
[0 1 2 3 4]
?
[1 2 3 4 5]
?
[2 2 2 2 2]


In [10]:
a = np.array([[1, 2, 3, 4, 5],[2 ,3 ,4 ,5 ,6],[3, 4, 5, 6, 7]])
for i, (v1, v2, v3, v4, v5) in enumerate(a):
    print(i, v1)

0 1
1 2
2 3


In [2]:
a = os.cpu_count()
print(a)

8


In [4]:
asdfaaaaaaaaaaaa = np.array([1, 2, 3, 4])
print(asdfaaaaaaaaaaaa)



[1 2 3 4]
